# Generated by Django 4.0.6 on 2022-07-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('minimum_amount', models.FloatField()),
                ('maximum_amount', models.FloatField()),
                ('minimum_duration', models.DurationField()),
                ('loan_type_id', models.UUIDField()),
                ('intrest_rate_value', models.FloatField()),
                ('minimum_monthly_salary', models.FloatField()),
            ],
        ),
    ]
