# Generated by Django 4.0.6 on 2022-07-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_api', '0003_loan_offers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_offers',
            name='Id',
        ),
    ]
