# Generated by Django 4.0.6 on 2022-07-31 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_api', '0005_loan_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('loan_category_id', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loan_applications',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan_applications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan_applications',
            name='declined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan_applications',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Loan_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('loan_category_id', models.UUIDField()),
                ('loan_type_id', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans_api.loan_categories')),
            ],
        ),
        migrations.AddField(
            model_name='loan_offers',
            name='Type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loans_api.loan_type'),
            preserve_default=False,
        ),
    ]
